# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    strime_encoding_api.helpers.files_action:
        class: StrimeEncodingAPI\EncodingBundle\Helpers\FilesAction
    app.tokens.action_listener:
        class: StrimeEncodingAPI\GlobalBundle\EventListener\TokenListener
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.tokens.exception_listener:
        class: StrimeEncodingAPI\GlobalBundle\EventListener\ExceptionListener
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    app.listener.command_exception:
        class: StrimeEncodingAPI\GlobalBundle\EventListener\ConsoleExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: console.exception }
